import { Product } from "@/types";

export const products: Product[] = [
  {
    id: "mab-90-balmer",
    name: "Máscara de Solda Automática MAB-90 Balmer",
    description: "Proteção e conforto para trabalhos de solda no dia a dia. Escurecimento automático.",
    price: 139.90,
    imageUrl: "https://images.unsplash.com/photo-1590959651373-a3db0f38a96b?auto=format&fit=crop&q=80&w=800",
    category: "Proteção",
    isFeatured: true,
  },
  {
    id: "esmerilhadeira-bosch",
    name: "Esmerilhadeira Angular Bosch GWS 850",
    description: "Potente e leve, ideal para cortes e desbastes em metais e concreto.",
    price: 359.00,
    imageUrl: "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&q=80&w=800",
    category: "Ferramentas",
    isFeatured: true,
  },
  {
    id: "parafusadeira-dewalt",
    name: "Parafusadeira/Furadeira DeWalt 20V MAX",
    description: "Alta performance para perfuração e fixação. Acompanha bateria e carregador.",
    price: 899.00,
    imageUrl: "https://images.unsplash.com/photo-1629198688000-71f23e745b6e?auto=format&fit=crop&q=80&w=800",
    category: "Ferramentas",
    isFeatured: true,
  },
  {
    id: "lavadora-alta-pressao",
    name: "Lavadora de Alta Pressão Kärcher K3",
    description: "Ideal para limpeza de quintais, carros e motos. Economia de água e energia.",
    price: 649.90,
    imageUrl: "https://images.unsplash.com/photo-1605515298946-d062f2e9da53?auto=format&fit=crop&q=80&w=800",
    category: "Jardinagem",
    isFeatured: false,
  },
  {
    id: "jogo-ferramentas-mayle",
    name: "Jogo de Ferramentas Mayle 110 Peças",
    description: "Kit completo para reparos domésticos e automotivos. Maleta resistente.",
    price: 289.90,
    imageUrl: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&q=80&w=800",
    category: "Kits",
    isFeatured: false,
  },
  {
    id: "furadeira-impacto-skil",
    name: "Furadeira de Impacto Skil 6664",
    description: "Potência de 550W para perfurações em concreto, madeira e metal.",
    price: 189.90,
    imageUrl: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&q=80&w=800",
    category: "Ferramentas",
    isFeatured: false,
  },
  {
    id: "serra-circular-makita",
    name: "Serra Circular Makita 1800W",
    description: "Cortes precisos em madeira. Design ergonômico e base de alumínio.",
    price: 749.00,
    imageUrl: "https://images.unsplash.com/photo-1566937169390-7be4c63b8a0e?auto=format&fit=crop&q=80&w=800",
    category: "Ferramentas",
    isFeatured: true,
  },
  {
    id: "aspirador-po-wap",
    name: "Aspirador de Pó e Água WAP GTW 10",
    description: "Versatilidade para limpar sólidos e líquidos. Compacto e potente.",
    price: 229.90,
    imageUrl: "https://images.unsplash.com/photo-1558317374-a354d5f6d4da?auto=format&fit=crop&q=80&w=800",
    category: "Limpeza",
    isFeatured: false,
  },
  {
    id: "caixa-ferramentas-plastica",
    name: "Caixa de Ferramentas Plástica 19 Pol",
    description: "Organize suas ferramentas com praticidade. Fecho metálico e bandeja removível.",
    price: 59.90,
    imageUrl: "https://images.unsplash.com/photo-1581147036324-c17ac41dfa6c?auto=format&fit=crop&q=80&w=800",
    category: "Organizadores",
    isFeatured: false,
  },
  {
    id: "compressor-ar-motomil",
    name: "Compressor de Ar Motomil 24L",
    description: "Ideal para pinturas, inflagens e limpezas. Motor de 2HP.",
    price: 899.90,
    imageUrl: "https://images.unsplash.com/photo-1622329367963-c59807576d1e?auto=format&fit=crop&q=80&w=800",
    category: "Equipamentos",
    isFeatured: true,
  }
];

